name: Update Repository Information

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'  # Runs daily
  push:
    branches:
      - main

jobs:
  update-repos:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update pushed_at for repositories
        run: |
          # Parse the JSON data and iterate through each repository
          for repo in $(jq -c '.[]' assets/repositories.json); do
            owner=$(echo $repo | jq -r '.owner')
            name=$(echo $repo | jq -r '.name')
            
            # Get the pushed_at information using GitHub API
            pushed_at=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          https://api.github.com/repos/$owner/$name | \
                          jq -r '.pushed_at')

            # Update the pushed_at information in the JSON file
            jq --arg owner "$owner" --arg name "$name" --arg pushed_at "$pushed_at" \
              'map(if .owner == $owner and .name == $name then . + { pushed_at: $pushed_at } else . end)' \
              assets/repositories.json > tmp.json && mv tmp.json assets/repositories.json
          done

      - name: Check if working tree is clean
        id: check_clean_working_tree
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "CLEAN_WORKING_TREE=false" >> $GITHUB_ENV
          else
            echo "CLEAN_WORKING_TREE=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes (If anything has updated)
        if: env.CLEAN_WORKING_TREE == 'false'
        run: |
          git config --local user.email "shadowsstride@gmail.com"
          git config --local user.name "SethHartman13"
          git add assets/repositories.json
          git commit -m "Update pushed_at for repositories"
          git push