name: Update Repository Information

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  workflow_run:
    workflows: ["Pages Build Workflow Name"]
    types:
      - completed

jobs:
  update-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Update Repository Information
        run: |
          # Parse the JSON data and iterate through each repository
          for repo in $(jq -c '.[]' repositories.json); do
            owner=$(echo $repo | jq -r '.owner')
            name=$(echo $repo | jq -r '.name')
            
            # Get the pushed_at information using GitHub API
            pushed_at=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          https://api.github.com/repos/$owner/$name | \
                          jq -r '.pushed_at')

            # Update the pushed_at information in the JSON file
            jq --arg owner "$owner" --arg name "$name" --arg pushed_at "$pushed_at" \
              '.[] | select(.owner == $owner and .name == $name) |= . + { pushed_at: $pushed_at }' \
              repositories.json > tmp.json && mv tmp.json repositories.json
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "shadowsstride@gmail.com"
          git config --local user.name "SethHartman13"
          git add repositories.json
          git commit -m "Update Update Repository Information"
          git push