name: Update Repositories

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  workflow_run:
    workflows: ["Pages Build Workflow Name", "Development Workflow Name"]
    types:
      - completed

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Info
        run: |
          echo "Fetching repository names from GitHub API..."
          curl -sSf "https://api.github.com/orgs/Shadow-Draconic-Development/repos" | \
          jq -r '.[] | .name' > repositories.tmp  # Fetch repository names from GitHub API
          cat repositories.tmp  # Print out fetched repository names for debugging

          echo "Contents of repositories.json before update:"
          cat repositories.json  # Display contents of repositories.json before update

      - name: Update Repositories JSON
        run: |
          echo "Updating repositories.json file..."
          # Loop through each repository name fetched from the JSON file
          while IFS= read -r repo; do
            echo "Processing repository: $repo"
            # Fetch existing status from repositories.json for the current repository
            existing_status=$(jq -r --arg repo "$repo" '.[] | select(.name == $repo) | .status' repositories.json)
            echo "Existing status for $repo: $existing_status"

            # If the repository exists in repositories.json, update its information
            if [ -n "$existing_status" ]; then
              echo "Repository $repo exists in repositories.json. Fetching updated information..."
              # Fetch updated repository information from GitHub API
              updated_info=$(curl -sSf "https://api.github.com/repos/Shadow-Draconic-Development/$repo" | \
                             jq --arg repo "$repo" '. | .owner = "Shadow-Draconic-Development" | .name = $repo | .updated = (.pushed_at) | del(.pushed_at)')
              echo "Updated info for $repo: $updated_info"

              # Merge existing status with updated repository information
              updated_info=$(jq --arg existing_status "$existing_status" '. + {status: $existing_status}' <<< "$updated_info")
              echo "Merged info for $repo: $updated_info"

              # Replace the existing repository information with the updated one
              jq --arg repo "$repo" --argjson updated_info "$updated_info" '. | map(if .name == $repo then . = $updated_info else . end)' repositories.json > repositories.json.tmp
              mv repositories.json.tmp repositories.json
              echo "Updated repository info for $repo in repositories.json"
            else
              echo "Repository $repo does not exist in repositories.json. Skipping..."
            fi
          done < repositories.tmp

          echo "Contents of repositories.json after update:"
          cat repositories.json  # Display contents of repositories.json after update
