name: Update Repositories

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Repositories JSON
        run: |
          curl -sSf "https://api.github.com/orgs/Shadow-Draconic-Development/repos" | \
          jq -r '.[] | .name' > repositories.tmp  # Fetch repository names from GitHub API

          # Loop through each repository name fetched from the JSON file
          while IFS= read -r repo; do
            # Fetch existing status from repositories.json for the current repository
            existing_status=$(jq -r --arg repo "$repo" '.[] | select(.name == $repo) | .status' repositories.json)

            # If the repository exists in repositories.json, update its information
            if [ -n "$existing_status" ]; then
              # Fetch updated repository information from GitHub API
              updated_info=$(curl -sSf "https://api.github.com/repos/Shadow-Draconic-Development/$repo" | \
                             jq --arg repo "$repo" '. | .owner = "Shadow-Draconic-Development" | .name = $repo | .updated = (.pushed_at) | del(.pushed_at)')

              # Merge existing status with updated repository information
              updated_info=$(jq --arg existing_status "$existing_status" '. + {status: $existing_status}' <<< "$updated_info")

              # Replace the existing repository information with the updated one
              jq --arg repo "$repo" --argjson updated_info "$updated_info" '. | map(if .name == $repo then . = $updated_info else . end)' repositories.json > repositories.json.tmp
              mv repositories.json.tmp repositories.json
            fi
          done < repositories.tmp
